spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      api-key: ${your-api-key}
      embedding:
       options:
         model: text-embedding-3-small
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv